# Experiments with embeddings

In [1]:
import numpy as np
from tabulate import tabulate

from embed import embed_one, embed_many

In [2]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [3]:
embedding = embed_one("Your text string goes here")

In [4]:
embedding

array([-6.9754184e-03, -5.3491648e-03,  1.1907940e-02, ...,
       -1.7028622e-02, -8.8358240e-05, -2.4030920e-02], dtype=float32)

In [5]:
type(embedding)

numpy.ndarray

In [6]:
cat = embed_one("cat")
gato = embed_one("gato")

In [7]:
np.dot(cat, gato)

0.8447504

In [8]:
np.dot(cat, embedding)

0.76458704

In [9]:
catrun_en = embed_one("The cat runs.")
catrun_es = embed_one("El gato corre.")
dogwalk_en = embed_one("The dog walks.")
dogwalk_es = embed_one("El perro camina.")

In [10]:
np.dot(catrun_en, catrun_es)

0.9224324

In [11]:
np.dot(catrun_en, embedding)

0.7650094

In [12]:
np.dot(dogwalk_en, dogwalk_es)

0.92638606

In [13]:
np.dot(catrun_en, dogwalk_en)

0.88560975

In [14]:
np.dot(catrun_es, dogwalk_es)

0.89643717

In [15]:
np.dot(catrun_en, dogwalk_es)

0.8421978

In [16]:
np.dot(catrun_es, dogwalk_en)

0.8305751

In [17]:
catrun_en.shape

(1536,)

In [18]:
many = embed_many([
    "Your text string goes here",
    "The cat runs.",
    "El gato corre.",
    "The dog walks.",
    "El perro camina.",
])
many.shape

(5, 1536)

In [19]:
many

array([[-6.92928350e-03, -5.33642201e-03,  1.18758921e-02, ...,
        -1.70174073e-02, -4.54713227e-05, -2.40475051e-02],
       [-9.06457007e-03, -4.09244280e-03, -1.10980421e-02, ...,
        -2.47713905e-02,  5.54583408e-03, -2.42741778e-02],
       [-1.42147215e-02, -2.92078988e-03,  3.90018802e-04, ...,
        -8.08201265e-03,  4.93654609e-03, -6.90483581e-03],
       [ 9.59877204e-03, -6.36116648e-03, -5.89548331e-03, ...,
        -1.23801986e-02, -3.47282301e-04, -1.70813799e-02],
       [ 3.45983449e-03, -7.59354141e-03,  1.42495893e-03, ...,
         4.55097703e-04, -8.73538014e-03, -6.12724526e-03]], dtype=float32)

In [20]:
np.dot(many[0], many[1])

0.7649304

In [21]:
np.dot(catrun_en, catrun_es)

0.9224324

In [22]:
small = np.array([[1, 2], [3, 4]])
small

array([[1, 2],
       [3, 4]])

In [23]:
small.transpose()

array([[1, 3],
       [2, 4]])

In [24]:
table = many @ many.transpose()
table

array([[1.0000004 , 0.76493055, 0.73437065, 0.7510821 , 0.7233679 ],
       [0.76493055, 1.0000005 , 0.92238605, 0.8856448 , 0.8423538 ],
       [0.73437065, 0.92238605, 1.0000001 , 0.8305839 , 0.8966306 ],
       [0.7510821 , 0.8856448 , 0.8305839 , 1.0000004 , 0.9264928 ],
       [0.7233679 , 0.8423538 , 0.8966306 , 0.9264928 , 0.99999976]],
      dtype=float32)

In [25]:
tabulate(table, tablefmt='html', floatfmt='.9f')

'<table>\n<tbody>\n<tr><td style="text-align: right;">1.000000358</td><td style="text-align: right;">0.764930546</td><td style="text-align: right;">0.734370649</td><td style="text-align: right;">0.751082122</td><td style="text-align: right;">0.723367929</td></tr>\n<tr><td style="text-align: right;">0.764930546</td><td style="text-align: right;">1.000000477</td><td style="text-align: right;">0.922386050</td><td style="text-align: right;">0.885644794</td><td style="text-align: right;">0.842353821</td></tr>\n<tr><td style="text-align: right;">0.734370649</td><td style="text-align: right;">0.922386050</td><td style="text-align: right;">1.000000119</td><td style="text-align: right;">0.830583870</td><td style="text-align: right;">0.896630585</td></tr>\n<tr><td style="text-align: right;">0.751082122</td><td style="text-align: right;">0.885644794</td><td style="text-align: right;">0.830583870</td><td style="text-align: right;">1.000000358</td><td style="text-align: right;">0.926492810</td></tr>\n<tr><td style="text-align: right;">0.723367929</td><td style="text-align: right;">0.842353821</td><td style="text-align: right;">0.896630585</td><td style="text-align: right;">0.926492810</td><td style="text-align: right;">0.999999762</td></tr>\n</tbody>\n</table>'