# Experiments with embeddings

In [1]:
import numpy as np
from tabulate import tabulate

from embed import embed_one, embed_many

In [2]:
np.array([1, 2, 3, 4], dtype=np.float32)

array([1., 2., 3., 4.], dtype=float32)

In [3]:
embedding = embed_one("Your text string goes here")

In [4]:
embedding

array([-6.9292835e-03, -5.3364220e-03,  1.1875892e-02, ...,
       -1.7017407e-02, -4.5471323e-05, -2.4047505e-02], dtype=float32)

In [5]:
type(embedding)

numpy.ndarray

In [6]:
cat = embed_one("cat")
gato = embed_one("gato")

In [7]:
np.dot(cat, gato)

0.8444619

In [8]:
np.dot(cat, embedding)

0.76415867

In [9]:
catrun_en = embed_one("The cat runs.")
catrun_es = embed_one("El gato corre.")
dogwalk_en = embed_one("The dog walks.")
dogwalk_es = embed_one("El perro camina.")

In [10]:
np.dot(catrun_en, catrun_es)

0.9224139

In [11]:
np.dot(catrun_en, embedding)

0.76497674

In [12]:
np.dot(dogwalk_en, dogwalk_es)

0.9269187

In [13]:
np.dot(catrun_en, dogwalk_en)

0.8857113

In [14]:
np.dot(catrun_es, dogwalk_es)

0.8966301

In [15]:
np.dot(catrun_en, dogwalk_es)

0.8422663

In [16]:
np.dot(catrun_es, dogwalk_en)

0.8305974

In [17]:
catrun_en.shape

(1536,)

In [18]:
many = embed_many([
    "Your text string goes here",
    "The cat runs.",
    "El gato corre.",
    "The dog walks.",
    "El perro camina.",
])
many.shape

(5, 1536)

In [19]:
many

array([[-6.9754184e-03, -5.3491648e-03,  1.1907940e-02, ...,
        -1.7028622e-02, -8.8358240e-05, -2.4030920e-02],
       [-9.0430975e-03, -4.0786345e-03, -1.1095160e-02, ...,
        -2.4764959e-02,  5.5921902e-03, -2.4191400e-02],
       [-1.4204165e-02, -2.9433765e-03,  4.0550550e-04, ...,
        -8.1148576e-03,  4.9277819e-03, -6.8172398e-03],
       [ 9.5597431e-03, -6.3604913e-03, -5.9328689e-03, ...,
        -1.2309198e-02, -3.6862658e-04, -1.7130248e-02],
       [ 3.4267190e-03, -7.4588875e-03,  1.3607008e-03, ...,
         4.5837829e-04, -8.7634120e-03, -6.1512413e-03]], dtype=float32)

In [20]:
np.dot(many[0], many[1])

0.7650559

In [21]:
np.dot(catrun_en, catrun_es)

0.9224139

In [22]:
small = np.array([[1, 2], [3, 4]])
small

array([[1, 2],
       [3, 4]])

In [23]:
small.transpose()

array([[1, 3],
       [2, 4]])

In [24]:
table = many @ many.transpose()
table

array([[0.99999976, 0.76505584, 0.7345198 , 0.75117296, 0.7233828 ],
       [0.76505584, 1.        , 0.9224138 , 0.8857111 , 0.8422562 ],
       [0.7345198 , 0.9224138 , 1.        , 0.8305976 , 0.8964369 ],
       [0.75117296, 0.8857111 , 0.8305976 , 1.0000002 , 0.9263847 ],
       [0.7233828 , 0.8422562 , 0.8964369 , 0.9263847 , 1.0000002 ]],
      dtype=float32)

In [25]:
tabulate(table, tablefmt='html', floatfmt='.9f')

'<table>\n<tbody>\n<tr><td style="text-align: right;">0.999999762</td><td style="text-align: right;">0.765055835</td><td style="text-align: right;">0.734519780</td><td style="text-align: right;">0.751172960</td><td style="text-align: right;">0.723382771</td></tr>\n<tr><td style="text-align: right;">0.765055835</td><td style="text-align: right;">1.000000000</td><td style="text-align: right;">0.922413826</td><td style="text-align: right;">0.885711074</td><td style="text-align: right;">0.842256188</td></tr>\n<tr><td style="text-align: right;">0.734519780</td><td style="text-align: right;">0.922413826</td><td style="text-align: right;">1.000000000</td><td style="text-align: right;">0.830597579</td><td style="text-align: right;">0.896436930</td></tr>\n<tr><td style="text-align: right;">0.751172960</td><td style="text-align: right;">0.885711074</td><td style="text-align: right;">0.830597579</td><td style="text-align: right;">1.000000238</td><td style="text-align: right;">0.926384687</td></tr>\n<tr><td style="text-align: right;">0.723382771</td><td style="text-align: right;">0.842256188</td><td style="text-align: right;">0.896436930</td><td style="text-align: right;">0.926384687</td><td style="text-align: right;">1.000000238</td></tr>\n</tbody>\n</table>'